# Generated by Django 2.0.2 on 2018-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='not completed', max_length=200),
        ),
    ]
